Homework 7. Networking
AnnGal/Navier pull request #10
Opened 2021-01-01 21:52 UTC by AnnGal

Api from https://www.themoviedb.org/

2021-01-03 13:03 UTC, an-yurii requested changes

2021-01-03 13:03 UTC, an-yurii commented on app/build.gradle
> +    productFlavors {
Для информации. Для нашего тестового примера можно было обойтись без различных вариантов сборки.

2021-01-03 13:03 UTC, an-yurii commented on app/build.gradle
> +            buildConfigField "String", "API_KEY", "\"c589a9f6e9e9d8b8b1a3612f1b750053\""
Параметры можно было просто добавить в `androi.defaultConfig`
```
    defaultConfig {
        applicationId "an.maguste.android.navier"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "IMAGE_URL", "\"https://image.tmdb.org/t/p/w500/\""
        buildConfigField "String", "BASE_URL", "\"https://api.themoviedb.org/3/\""
        buildConfigField "String", "API_KEY", "\"c589a9f6e9e9d8b8b1a3612f1b750053\""
    }
```

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +private const val API_KEY_HEADER = "api_key"
Нужно бы перенести внутрь класса MovieApiHeaderInterceptor

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +interface MovieApiService {
Не стоит увлекаться складыванием всего подряд в один файл. Разложи по разным файлам: MovieApiHeaderInterceptor, MovieApiService и все относящееся к Retrofit.

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +object MovieDbApiService {
Разделяемым ресурсом является Retrofit. Его нужно конструировать как сингтон, сервисы уже строить по мере необходимости. 

Название класса какое-то странное) Общепринятая практика: использовать `Db` в сущностях, которые работают с базой данных.

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +private val client = OkHttpClient().newBuilder()
Перемести внутрь класса, который будет возвращать Retrofit

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +private val json = Json {
Перемести внутрь класса, который будет возвращать Retrofit

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Genre.kt
> +
```suggestion
    val name: String
) : Parcelable
```

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Movie.kt
> +        val genreIds: List<Int>? = listOf(),
Так как ты используешь значение по умолчанию, используй not null тип `List<Int>`
```suggestion
        val genreIds: List<Int> = listOf(),
```

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Movie.kt
> +        @SerialName("overview")
Нужно сверить возможные значения, которые возвращает сервис https://developers.themoviedb.org/3/movies/get-movie-details
Например, согласно документации, overview может возвращать string or null

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +    suspend fun getGenres(@Query(API_KEY_HEADER) key: String = BuildConfig.API_KEY): GenresJson
На мой взгляд, вместо API_KEY_HEADER можно использовать строковую константу "api_key"
К тому же, в данном случае, это - не ключ заголовка

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Movie.kt
> +        val genreIds: List<Int>? = listOf(),
В твоем объекте появились "дубликаты" genreIds и genres, потому что этот класс пытается делать несколько вещей. С одной стороны, он как Dto (data transfer object) получает данные по сети, с другой стороны, как модель предоставляет данные пользователю. 

Обрати внимание на то, как было реализовано в файле JsonLoad.kt Было две сущности: одна - для парсинга из Json, вторая - модель данных. B данные маппились из одной структуры в другую. 

Нужно сделать два объекта: MovieDto (со списком идентификаторов жанров) и Movie (со списком жанров текстом).

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Movie.kt
> +        val actors: List<Actor>? = listOf(),
Список актеров можно убрать из фильма. Это - отдельная коллекция объектов, ее нужно загрузить на экране с информацией о фильме по идентификатору фильма
https://developers.themoviedb.org/3/movies/get-movie-credits

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Movie.kt
> +@Serializable
Формат json позволяет загружать меньше данных, чем есть в json. Тебе необходимы только: идентификатор, жанры, название, рейтинг, количество оценок, описание, постер и фоновое изображение. Остальное можно спокойно проигнорировать.

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/FragmentMoviesDetails.kt
> +    private var movieId: Int = 0
Нужно было оставить передачу фильма как она была. Потому что вся информация, за исключением списка актеров, уже загружена в списке. На этом экране нужно только подгрузить и показать список актеров. Это можно сделать отдельной коллекцией, необязательно сохранять ее в объекте - Movie.

2021-01-03 13:03 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/MoviesDetailsViewModel.kt
> +                val resultRequest = MovieDbApiService.retrofitService.getMovie(movieId = movieId)
Сервис нужно передавать через параметры конструктора как поступали с контекстом.

2021-01-03 21:07 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +object MovieDbApiService {
Упс. Сначала скопировала название API, потом так же подумала про DB и поменяла название файла. А в объекте забыла DB убрать)

2021-01-04 07:27 UTC, an-yurii requested changes

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/RetrofitService.kt
> +    private val client = OkHttpClient().newBuilder()
Свойства класса инициализируются при его создании. Нужно делать ленивую загрузку.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/RetrofitService.kt
> +    val movieApi: MovieApi = retrofit.create(MovieApi::class.java)
Общий разделяемый ресурс - retrofit. В приложении могут быть несколько различных api
```
object RetrofitService {
    
    @ExperimentalSerializationApi
    val retrofit: Retrofit by lazy {
        Retrofit.Builder()
            .client(createClient())
            .baseUrl(BuildConfig.BASE_URL)
            .addConverterFactory(createJson().asConverterFactory("application/json".toMediaType()))
            .build()
    }

    private fun createClient() = OkHttpClient().newBuilder()
        .addInterceptor(MovieApiHeaderInterceptor())
        .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
        .build()

    private fun createJson() = Json {
        ignoreUnknownKeys = true
    }
}
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/MoviesDetailViewModelFactory.kt
> +        MoviesDetailsViewModel::class.java -> MoviesDetailsViewModel(apiService = RetrofitService.movieApi)
```suggestion
        MoviesListViewModel::class.java -> MoviesListViewModel(
            apiService = RetrofitService.retrofit.create()
        )
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/RetrofitService.kt
> +object RetrofitService {
Это - холдер. К тому же, слово сервис ассоциируется с Андроид сервисами.
```suggestion
object RetrofitHolder {
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +package an.maguste.android.navier.api
Переименуй файл в `MovieApi.kt`

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiService.kt
> +    @GET("movie/{movie_id}/credits")
Лучше будет - написать комментарий в формате JavaDoc
```suggestion
    /**
     * example: https://api.themoviedb.org/3/movie/{movie_id}/credits?api_key=<<api_key>>&language=en-US
     */
    @GET("movie/{movie_id}/credits")
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/MovieApiHeaderInterceptor.kt
> +        Log.d("RetrofitTry", "set header request= ${request.header(API_KEY_HEADER)}")
Поменяй порядок интерсепторов и заголовок начнет логироваться.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +data class ActorsListDto(
Разный подход к именованию. Переименуй `ActorsListDto ` -> `ActorsDto `

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +package an.maguste.android.navier.api
Переименуй файл в соответствии с тем, что в нем находится `MovieApiDto.kt`

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +    val genres: List<Genre>
Используешь сущность доменной модели. Нужно использовать Dto.
Так как в приложении не требуется выполнять каких-либо манипуляций с жанрами, в доменной модели жанры могут быть представлены строкой или списком строк.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +    val results: List<MovieDto>? = null
В документации к методу API указано, что всегда возвращается массив объектов
```suggestion
    val results: List<MovieDto>
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +        get() = poster?.let { BuildConfig.IMAGE_URL + poster }
Эти свойства выходят за рамки сетевого слоя. Правильнее их будет заполнить во время преобразования MovieDto в Movie.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +    @SerialName("id")
Аннотации SerialName можно опускать, если имя свойства класса совпадает с ключем в json. Обязательно нужно указывать аннотации, когда используется минификатор (proguard и т.п.)

У тебя в части Dto отсутствуют аннотации.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +    val imageLink: String?
Это свойство выходит за рамки сетевого слоя. Правильнее его будет заполнить во время преобразования ActorDto в Actor.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Actor.kt
> +@Serializable
Так как объект Actor "живет" в рамках одного экрана и не сериализуется, не нужны аннотации Parcelize и Serializable

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/Genre.kt
> +data class Genre(
Я бы избавился от этого класса. Так как нам нужен только список названий.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/JsonLoad.kt
>  package an.maguste.android.navier.data
Загрузка из файла нам больше не нужна. Этот файл нужно удалить.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/movieslist/FragmentMoviesList.kt
> +import an.maguste.android.navier.data.State
State не относится к слою данных. Это - часть паттерна MVVM.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/movieslist/MovieAdapter.kt
>          }
Нужно заменить на обычный if
```suggestion
        if (movie.adult) {
           itemView.resources.getString(R.string.age_rating_default)
        } else {
            binding.ageRating.visibility = View.INVISIBLE
        }
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/movieslist/MovieAdapter.kt
>          }
При компиляции в java код добавляется лишняя проверка
```
      boolean var2 = movie.getAdult();
      TextView var8;
      View var10001;
      if (var2) {
         var8 = this.binding.ageRating;
         Intrinsics.checkNotNullExpressionValue(var8, "binding.ageRating");
         var10001 = this.itemView;
         Intrinsics.checkNotNullExpressionValue(var10001, "itemView");
         var8.setText((CharSequence)var10001.getResources().getString(1900094));
      } else if (!var2) {
         var8 = this.binding.ageRating;
         Intrinsics.checkNotNullExpressionValue(var8, "binding.ageRating");
         var8.setVisibility(4);
      }
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/movieslist/MoviesListViewModelFactory.kt
> +        MoviesListViewModel::class.java -> MoviesListViewModel(apiService = RetrofitService.movieApi)
```suggestion
        MoviesListViewModel::class.java -> MoviesListViewModel(
            apiService = RetrofitHolder.retrofit.create()
        )
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonConverter.kt
> +suspend fun convertFromJsonToMovie(moviesDto: List<MovieDto>, genres: List<Genre>): List<Movie> =
Предлагаю разделить на два файла. И переименовать в `convertMovieDtoToDomain` так десериализацию из json для нас уже сделал retrofit

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/MoviesDetailsViewModel.kt
> +    val movie: LiveData<Movie> get() = _movie
Зачем гонять Movie через  вью модель? Нужно убрать. Этот объект передается через параметры фрагмента.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/api/JsonApiClasses.kt
> +    val actors: List<ActorDto>? = null
Согласно описанию метода, всегда возвращается массив объектов
```suggestion
    val actors: List<ActorDto>
```

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/FragmentMoviesDetails.kt
> +        movie?.let {
С какой целью это делать? Вся необходимая информация о фильме уже есть.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/FragmentMoviesDetails.kt
> +                adult -> {
Используй if

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/FragmentMoviesDetails.kt
> +                rating = ratings / 2
Нужно перенести адаптацию рейтинга в маппинг из MovieDot в Movie. Чтобы во вью было минимум логики.

2021-01-04 07:27 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/FragmentMoviesDetails.kt
> +        when (actors.isNotEmpty()) {
Замени на простой if.

2021-01-06 07:45 UTC, an-yurii approved these changes
Вот, сейчас - отлично)

2021-01-06 10:34 UTC, AnnGal commented
Урааа)

2021-01-06 10:34 UTC, merged