add FragmentMoviesDetails and FragmentMoviesList
AnnGal/Navier pull request #6
Opened 2020-11-25 08:06 UTC by AnnGal

MovieDetailsActivity was replaced by FragmentMoviesDetails 
Also navigation between fragments were added (via supportFragmentManager)

2020-11-26 03:42 UTC, an-yurii requested changes
Отличная работа) Нужно поправить незначительные замечания.

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +private const val ARG_MOVIE_ID = "movie_id"
Нужно перенести в `companion object`

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +        fun newInstance(param1: String) =
Переменным нужно давать горящие имена. Переименуй, пожалуйста.

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +        listener = context as ChangeFragment
Если активити не будет имплементировать интерфейс `ChangeFragment`, приложение упадет. Поменяй на `as?`.

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/MainActivity.kt
> +import an.maguste.android.navier.model.ChangeFragment
По-моему, это - лишний импорт.

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/MainActivity.kt
> +            replace<FragmentMoviesDetails>(R.id.fragment_place)
Нужен add вместо replace. Replace удаляет `FragmentMoviesList` и возвращаться некуда.

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesList.kt
> +        listener = context as ChangeFragment
```suggestion
        listener = context as? ChangeFragment
```

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/res/drawable/gradient_view_card.xml
> +        android:startColor="#191926" />
Нужно бы добавить в палитру.

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/MainActivity.kt
>          setContentView(R.layout.activity_main)
Для информации) Если активити пустая и отображает только фрагмент, можно обойтись без вызова `setContentView(...)`. 
Можно воспользоваться `android.R.id.content`
```
add<FragmentMoviesList>(android.R.id.content)
```

2020-11-26 03:42 UTC, an-yurii commented on app/src/main/res/values/styles.xml
> +        <item name="android:maxHeight">8dip</item>
```suggestion
        <item name="android:minHeight">8dp</item>
        <item name="android:maxHeight">8dp</item>
```

2020-11-26 03:42 UTC, an-yurii commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.1'
Мне кажется, что эти зависимости - лишние. Можно без них.

2020-11-26 04:18 UTC, an-yurii requested changes

2020-11-26 04:18 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/MainActivity.kt
> +            replace<FragmentMoviesDetails>(R.id.fragment_place)
Достаточно просто
```
            add<FragmentMoviesDetails>(R.id.fragment_place)
            addToBackStack(null)
```

2020-11-26 04:18 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/MainActivity.kt
> +                setReorderingAllowed(true)
Вызов - излишен.

2020-11-26 04:18 UTC, an-yurii commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.1'
Добавь импорт `implementation "androidx.fragment:fragment-ktx:1.2.5"`

2020-11-26 04:18 UTC, an-yurii commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:background="@drawable/gradient_radial_view_card" />
Мне непонятно назначение этого элемента. Убрал, разницы не увидел.

2020-11-26 04:18 UTC, an-yurii commented on app/src/main/res/layout/fragment_movies_list.xml
> +                <FrameLayout
Этот элемент - излишний, добавляет глубину верстки. Просто привяжи вью, накладывающую градиент, к границам изображения `@+id/frameTitleImage`

2020-11-26 08:15 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +        listener = context as ChangeFragment
Спасибо! Даже не подумала о таком

2020-11-26 08:55 UTC, AnnGal commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:background="@drawable/gradient_radial_view_card" />
В фигме, на карточке (на самой карточке, не на постере) стоит "Radial Gradient". 
Все ломала голову - нужен он или нет, и какой должен быть радиус. В итоге добавила, чтобы потренироваться.
Но то ли я с радиусом не угадала, то ли там такое затемнение, что им можно пренебречь - тоже подумалось, что это бессмысленная штука.

2020-11-26 09:06 UTC, AnnGal commented on app/src/main/res/layout/fragment_movies_list.xml
> +                <FrameLayout
Хм.. а ведь правда..

2020-11-26 09:36 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/MainActivity.kt
>          setContentView(R.layout.activity_main)
Спасибо! Поэкспериментировала, действительно работает.

2020-11-27 03:36 UTC, an-yurii approved these changes

2020-11-27 09:03 UTC, merged