Homework 6. Architecture mvvm
AnnGal/Navier pull request #9
Opened 2020-12-22 13:54 UTC by AnnGal

Set navigation and move to Model-View-ViewModel

2020-12-26 09:02 UTC, an-yurii requested changes
Немного перемудрила. Нужно доработать.
Молодец, что стараешься смотреть шире, чем предполагает данный курс)

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +    private lateinit var viewModel: FragmentMoviesDetailsVM
Не стоит использовать сокращения в именах классов и переменных, если это не общепринятое сокращение. На мой взгляд, `MoviesDetailsViewModel` будет долее подходящим вариантом.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:src="@drawable/ic_no_asset" />
По-моему, что что-то напутано с ресурсами `ic_no_asset`есть и векторный xml, и png. Кажется, что от png можно обойтись.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintLeft_toLeftOf="parent"
```suggestion
            app:layout_constraintStart_toStartOf="parent"
```

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/res/layout/fragment_movies_list.xml
> +            app:layout_constraintRight_toRightOf="parent"
```suggestion
            app:layout_constraintEnd_toEndOf="parent"
```

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FactoryVM.kt
> +class MoviesDetailViewModelFactory(private val movie: Movie) : ViewModelProvider.Factory{
Эти классы нужно разделить по разным файлам.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FactoryVM.kt
> +package an.maguste.android.navier.mvvm
Для навигации по коду приложения будет удобнее сложить в один пакет все классы, которые относятся к одному экрану: фрагмент, вью модель, вью модель фабрику, адаптеры для ресайклера и т.д. 

Идея в том, чтобы все относящееся к одному классу лежало в одной кучке)

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FragmentMoviesDetailsVM.kt
> +class FragmentMoviesDetailsVM(private val movie: Movie) : ViewModel() {
Избегай использования аббревиатур

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FragmentMoviesListVM.kt
> +    val moviesData: LiveData<List<Movie>> get() = _moviesData
`moviesData` можно просто `movies`

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FragmentMoviesListVM.kt
> +    init {
Очень плохое решение - вызывать какие-либо методы в конструкторе. Конструктор должен быть очень простым, заниматься только инициализацией переменных.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FragmentMoviesListVM.kt
> +    private fun parseMovieAsset() {
Этот метод нужно вызвать явно из фрагмента. Например, из метода `onViewCreated` Вью должно сказать своей вью модели, когда нужно начинать загрузку данных.
И метод можно переименовать согласно его функции в `loadMovies`

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/mvvm/FragmentMoviesListVM.kt
> +    private val _selectedMovie = MutableLiveData<Movie>()
Выбранный элемент не нужен во вью модели со списком.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesList.kt
> +    private lateinit var viewModel: FragmentMoviesListVM
Обрати внимание, как сделана инициализация в воркшопе
```
private val viewModel: Workshop2SolutionViewModel by viewModels { Workshop2SolutionViewModelFactory() }
```

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesList.kt
> +        binding.recyclerView.adapter = MovieAdapter(OnMovieClickListener {
Я не пойму: зачем нужно сохранять выбранный фильм во вью модели?

В качестве листенера, ты можешь передать любой объект, который имплементирует интерфейс `OnMovieClickListener`. В качестве такого объекта, можно передать навигатор, который управляет переключением экранов.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesList.kt
> +        viewModel.selectedMovie.observe(viewLifecycleOwner,  {
Нет необходимости гонять данные через вью модель. Можно просто обработать вызов колбека, как и было реализовано в рамках предыдущей домашки. Если ты хочешь попробовать навигатор, достаточно было переделать вызов фрагмента с информацией о фильме.

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesList.kt
> +            if ( null != it ) {
Лишняя проверка на null. Ты уже получаешь not null объект Movie

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/data/JsonLoad.kt
> +private suspend fun loadGenres(context: Context,
Чем не устроил диспетчер `Dispatchers.IO`?

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +        val viewModelFactory = MoviesDetailViewModelFactory(movie)
Это - статический фрагмент. В этом месте у тебя уже есть вся информация о фильме, ее нужно просто показать. Т.е. ничего не нужно было менять с предыдущей домашки)

2020-12-26 09:02 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +            requireActivity().onBackPressed()
Я не пользовался навигаций от гугла. Не могу утверждать наверняка, но как-то странно смотрится возврат к предыдущему фрагменту через `onBackPressed`. Если переходишь на решение для навигации, используй ее везде.

2020-12-27 09:29 UTC, AnnGal commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:src="@drawable/ic_no_asset" />
Все верно, почему-то никогда об этом не задумывалась. Сгенерировала картинку средствами Android Studio - видимо ide специально генерит с излишком

2020-12-27 09:48 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/mvvm/FactoryVM.kt
> +package an.maguste.android.navier.mvvm
Внезапно чрезвычайно сложно оказалось преломить себя и сделать три файла, да ещё в отдельной папке для каждого фрагмента. Это кажется безумным расточительством!
Но чем больше логики предполагается вносить в view model и автономнее становится, тем оправданнее такая разбивка кажется

2020-12-27 09:57 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/data/JsonLoad.kt
> +private suspend fun loadGenres(context: Context,
Мне захотелось, чтобы он был настраиваемым, брался с ViewModel) Верну обратно!

2020-12-27 10:35 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/mvvm/FragmentMoviesListVM.kt
> +    private val _selectedMovie = MutableLiveData<Movie>()
Честно говоря, я тогда решила упереться рогом и попробовать объединить гугловскую навигацию + парселизацию + viewmodel как сделали именно гугл в обучающем уроке. Это кидание данных во вью модель и подписка на переменную тоже кажется излишней.  Но раз все во вью модель, так все во вью модель - решила сделать как они)
В общем <s>с удовольствием</s> выпилила этот кусочек и поставила прыжок с фрагмента на фрагмент через навигацию напрямую

2020-12-27 10:39 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesList.kt
> +    private lateinit var viewModel: FragmentMoviesListVM
Поправлено!

2020-12-27 10:46 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +            requireActivity().onBackPressed()
Тут я спасовала и пока пошла по легкому пути... 
Можно это останется мне на подумать в будущем?
Дело в том, что гугл навигатор захватывает тулбар на активити и подрисовывает "гамбургер иконку" и иконку "стрелка назад" самостоятельно. Этим не очень удобен для кастомного интерфейса. Наверное, мне придется делать свой тулбар и ставить его на фрагменты или подменять стиль иконок и текст - тут я немного затормозила и ещё не поняла как лучше сделать.

2020-12-27 10:48 UTC, AnnGal commented on app/src/main/java/an/maguste/android/navier/FragmentMoviesDetails.kt
> +        val viewModelFactory = MoviesDetailViewModelFactory(movie)
Хочется закинуть навигацию, как в реальных проектах) Но если это мешается для проверки - верну назад)

2020-12-28 14:46 UTC, an-yurii approved these changes

2020-12-28 14:46 UTC, an-yurii commented on app/src/main/java/an/maguste/android/navier/moviesdetail/FragmentMoviesDetails.kt
> +    private lateinit var viewModel: MoviesDetailsViewModel
Вью модель излишня для статического экрана.

2020-12-28 14:50 UTC, merged